openapi: 3.0.1
info:
  title: Vehicle Rental System API
  description: API for managing vehicles, reservations, and users in a rental system.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local Development Server

paths:
  /cars:
    get:
      summary: Get a list of vehicles
      responses:
        200:
          description: A list of vehicles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'

  /cars/{carId}:
    get:
      summary: Get a specific vehicle by ID
      parameters:
        - name: carId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: The requested vehicle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'

  /reservations:
    post:
      summary: Create a new reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
      responses:
        201:
          description: The newly created reservation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'

  /users:
    get:
      summary: Get a list of users
      responses:
        200:
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

components:
  schemas:
    Car:
      type: object
      properties:
        id:
          type: string
        make:
          type: string
        model:
          type: string
        year:
          type: integer
        color:
          type: string
        engine:
          type: string
        transmission:
          type: string
        price:
          type: number
        vin:
          type: string
        ownerId:
          type: int
        fuelType:
          type: string


    Reservation:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        carId:
          type: string
        fromDate:
          type: string
          format: date
        toDate:
          type: string
          format: date
        pickUpLocation:
          type: string
        dropOffLocation:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        rsaId:
          type: string
